// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: ctrlmsg.proto

package ctrlmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerAddr string `protobuf:"bytes,1,opt,name=server_addr,json=serverAddr,proto3" json:"server_addr,omitempty"`
	Cluster    string `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ctrlmsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ctrlmsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_ctrlmsg_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetServerAddr() string {
	if x != nil {
		return x.ServerAddr
	}
	return ""
}

func (x *RegisterRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // redirect , disconnect
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ctrlmsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ctrlmsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_ctrlmsg_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ctrlmsg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ctrlmsg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_ctrlmsg_proto_rawDescGZIP(), []int{2}
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ctrlmsg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ctrlmsg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_ctrlmsg_proto_rawDescGZIP(), []int{3}
}

type PeerInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     uint32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *PeerInfoRequest) Reset() {
	*x = PeerInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ctrlmsg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfoRequest) ProtoMessage() {}

func (x *PeerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ctrlmsg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfoRequest.ProtoReflect.Descriptor instead.
func (*PeerInfoRequest) Descriptor() ([]byte, []int) {
	return file_ctrlmsg_proto_rawDescGZIP(), []int{4}
}

func (x *PeerInfoRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PeerInfoRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PeerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerId     string `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	ServerAddr string `protobuf:"bytes,2,opt,name=server_addr,json=serverAddr,proto3" json:"server_addr,omitempty"`
	Cluster    string `protobuf:"bytes,3,opt,name=cluster,proto3" json:"cluster,omitempty"`
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ctrlmsg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ctrlmsg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_ctrlmsg_proto_rawDescGZIP(), []int{5}
}

func (x *PeerInfo) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *PeerInfo) GetServerAddr() string {
	if x != nil {
		return x.ServerAddr
	}
	return ""
}

func (x *PeerInfo) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

type PeerInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Finished bool        `protobuf:"varint,1,opt,name=finished,proto3" json:"finished,omitempty"`
	Infos    []*PeerInfo `protobuf:"bytes,2,rep,name=infos,proto3" json:"infos,omitempty"`
}

func (x *PeerInfoResponse) Reset() {
	*x = PeerInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ctrlmsg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfoResponse) ProtoMessage() {}

func (x *PeerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ctrlmsg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfoResponse.ProtoReflect.Descriptor instead.
func (*PeerInfoResponse) Descriptor() ([]byte, []int) {
	return file_ctrlmsg_proto_rawDescGZIP(), []int{6}
}

func (x *PeerInfoResponse) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *PeerInfoResponse) GetInfos() []*PeerInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

type ReqeustHead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerId string `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
}

func (x *ReqeustHead) Reset() {
	*x = ReqeustHead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ctrlmsg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqeustHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqeustHead) ProtoMessage() {}

func (x *ReqeustHead) ProtoReflect() protoreflect.Message {
	mi := &file_ctrlmsg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqeustHead.ProtoReflect.Descriptor instead.
func (*ReqeustHead) Descriptor() ([]byte, []int) {
	return file_ctrlmsg_proto_rawDescGZIP(), []int{7}
}

func (x *ReqeustHead) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type ResponseHead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerId  string `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Code    uint32 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ResponseHead) Reset() {
	*x = ResponseHead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ctrlmsg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseHead) ProtoMessage() {}

func (x *ResponseHead) ProtoReflect() protoreflect.Message {
	mi := &file_ctrlmsg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseHead.ProtoReflect.Descriptor instead.
func (*ResponseHead) Descriptor() ([]byte, []int) {
	return file_ctrlmsg_proto_rawDescGZIP(), []int{8}
}

func (x *ResponseHead) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *ResponseHead) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResponseHead) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CtrlReqeust struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head *ReqeustHead `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	// Types that are assignable to RequestPayload:
	//	*CtrlReqeust_Register
	//	*CtrlReqeust_Heartbeat
	//	*CtrlReqeust_PeerInfo
	RequestPayload isCtrlReqeust_RequestPayload `protobuf_oneof:"RequestPayload"`
}

func (x *CtrlReqeust) Reset() {
	*x = CtrlReqeust{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ctrlmsg_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CtrlReqeust) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtrlReqeust) ProtoMessage() {}

func (x *CtrlReqeust) ProtoReflect() protoreflect.Message {
	mi := &file_ctrlmsg_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtrlReqeust.ProtoReflect.Descriptor instead.
func (*CtrlReqeust) Descriptor() ([]byte, []int) {
	return file_ctrlmsg_proto_rawDescGZIP(), []int{9}
}

func (x *CtrlReqeust) GetHead() *ReqeustHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (m *CtrlReqeust) GetRequestPayload() isCtrlReqeust_RequestPayload {
	if m != nil {
		return m.RequestPayload
	}
	return nil
}

func (x *CtrlReqeust) GetRegister() *RegisterRequest {
	if x, ok := x.GetRequestPayload().(*CtrlReqeust_Register); ok {
		return x.Register
	}
	return nil
}

func (x *CtrlReqeust) GetHeartbeat() *HeartbeatRequest {
	if x, ok := x.GetRequestPayload().(*CtrlReqeust_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

func (x *CtrlReqeust) GetPeerInfo() *PeerInfoRequest {
	if x, ok := x.GetRequestPayload().(*CtrlReqeust_PeerInfo); ok {
		return x.PeerInfo
	}
	return nil
}

type isCtrlReqeust_RequestPayload interface {
	isCtrlReqeust_RequestPayload()
}

type CtrlReqeust_Register struct {
	Register *RegisterRequest `protobuf:"bytes,2,opt,name=register,proto3,oneof"`
}

type CtrlReqeust_Heartbeat struct {
	Heartbeat *HeartbeatRequest `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type CtrlReqeust_PeerInfo struct {
	PeerInfo *PeerInfoRequest `protobuf:"bytes,4,opt,name=peer_info,json=peerInfo,proto3,oneof"`
}

func (*CtrlReqeust_Register) isCtrlReqeust_RequestPayload() {}

func (*CtrlReqeust_Heartbeat) isCtrlReqeust_RequestPayload() {}

func (*CtrlReqeust_PeerInfo) isCtrlReqeust_RequestPayload() {}

type CtrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head *ResponseHead `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	// Types that are assignable to ResponsePayload:
	//	*CtrlResponse_Register
	//	*CtrlResponse_Heartbeat
	//	*CtrlResponse_PeerInfo
	ResponsePayload isCtrlResponse_ResponsePayload `protobuf_oneof:"ResponsePayload"`
}

func (x *CtrlResponse) Reset() {
	*x = CtrlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ctrlmsg_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CtrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtrlResponse) ProtoMessage() {}

func (x *CtrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ctrlmsg_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtrlResponse.ProtoReflect.Descriptor instead.
func (*CtrlResponse) Descriptor() ([]byte, []int) {
	return file_ctrlmsg_proto_rawDescGZIP(), []int{10}
}

func (x *CtrlResponse) GetHead() *ResponseHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (m *CtrlResponse) GetResponsePayload() isCtrlResponse_ResponsePayload {
	if m != nil {
		return m.ResponsePayload
	}
	return nil
}

func (x *CtrlResponse) GetRegister() *RegisterResponse {
	if x, ok := x.GetResponsePayload().(*CtrlResponse_Register); ok {
		return x.Register
	}
	return nil
}

func (x *CtrlResponse) GetHeartbeat() *HeartbeatResponse {
	if x, ok := x.GetResponsePayload().(*CtrlResponse_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

func (x *CtrlResponse) GetPeerInfo() *PeerInfoResponse {
	if x, ok := x.GetResponsePayload().(*CtrlResponse_PeerInfo); ok {
		return x.PeerInfo
	}
	return nil
}

type isCtrlResponse_ResponsePayload interface {
	isCtrlResponse_ResponsePayload()
}

type CtrlResponse_Register struct {
	Register *RegisterResponse `protobuf:"bytes,2,opt,name=register,proto3,oneof"`
}

type CtrlResponse_Heartbeat struct {
	Heartbeat *HeartbeatResponse `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type CtrlResponse_PeerInfo struct {
	PeerInfo *PeerInfoResponse `protobuf:"bytes,4,opt,name=peer_info,json=peerInfo,proto3,oneof"`
}

func (*CtrlResponse_Register) isCtrlResponse_ResponsePayload() {}

func (*CtrlResponse_Heartbeat) isCtrlResponse_ResponsePayload() {}

func (*CtrlResponse_PeerInfo) isCtrlResponse_ResponsePayload() {}

var File_ctrlmsg_proto protoreflect.FileDescriptor

var file_ctrlmsg_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x74, 0x72, 0x6c, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x63, 0x74, 0x72, 0x6c, 0x6d, 0x73, 0x67, 0x22, 0x4c, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x22, 0x2a, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x12, 0x0a, 0x10, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62,
	0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x42, 0x0a, 0x0f, 0x50,
	0x65, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22,
	0x5e, 0x0a, 0x08, 0x50, 0x65, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x70,
	0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x65,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x61,
	0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x41, 0x64, 0x64, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x22,
	0x57, 0x0a, 0x10, 0x50, 0x65, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12,
	0x27, 0x0a, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x63, 0x74, 0x72, 0x6c, 0x6d, 0x73, 0x67, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x26, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x65,
	0x75, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x55, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xf5, 0x01, 0x0a, 0x0b, 0x43, 0x74, 0x72, 0x6c,
	0x52, 0x65, 0x71, 0x65, 0x75, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x74, 0x72, 0x6c, 0x6d, 0x73, 0x67, 0x2e,
	0x52, 0x65, 0x71, 0x65, 0x75, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61,
	0x64, 0x12, 0x36, 0x0a, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x74, 0x72, 0x6c, 0x6d, 0x73, 0x67, 0x2e, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x09, 0x68, 0x65, 0x61,
	0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63,
	0x74, 0x72, 0x6c, 0x6d, 0x73, 0x67, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74,
	0x62, 0x65, 0x61, 0x74, 0x12, 0x37, 0x0a, 0x09, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x74, 0x72, 0x6c, 0x6d, 0x73,
	0x67, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x48, 0x00, 0x52, 0x08, 0x70, 0x65, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x10, 0x0a,
	0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22,
	0xfb, 0x01, 0x0a, 0x0c, 0x43, 0x74, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x29, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x63, 0x74, 0x72, 0x6c, 0x6d, 0x73, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x48, 0x65, 0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x37, 0x0a, 0x08, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x63, 0x74, 0x72, 0x6c, 0x6d, 0x73, 0x67, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x12, 0x3a, 0x0a, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x74, 0x72, 0x6c, 0x6d, 0x73,
	0x67, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74,
	0x12, 0x38, 0x0a, 0x09, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x74, 0x72, 0x6c, 0x6d, 0x73, 0x67, 0x2e, 0x50, 0x65,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00,
	0x52, 0x08, 0x70, 0x65, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x11, 0x0a, 0x0f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x0b, 0x5a,
	0x09, 0x2e, 0x2f, 0x63, 0x74, 0x72, 0x6c, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_ctrlmsg_proto_rawDescOnce sync.Once
	file_ctrlmsg_proto_rawDescData = file_ctrlmsg_proto_rawDesc
)

func file_ctrlmsg_proto_rawDescGZIP() []byte {
	file_ctrlmsg_proto_rawDescOnce.Do(func() {
		file_ctrlmsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_ctrlmsg_proto_rawDescData)
	})
	return file_ctrlmsg_proto_rawDescData
}

var file_ctrlmsg_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_ctrlmsg_proto_goTypes = []interface{}{
	(*RegisterRequest)(nil),   // 0: ctrlmsg.RegisterRequest
	(*RegisterResponse)(nil),  // 1: ctrlmsg.RegisterResponse
	(*HeartbeatRequest)(nil),  // 2: ctrlmsg.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 3: ctrlmsg.HeartbeatResponse
	(*PeerInfoRequest)(nil),   // 4: ctrlmsg.PeerInfoRequest
	(*PeerInfo)(nil),          // 5: ctrlmsg.PeerInfo
	(*PeerInfoResponse)(nil),  // 6: ctrlmsg.PeerInfoResponse
	(*ReqeustHead)(nil),       // 7: ctrlmsg.ReqeustHead
	(*ResponseHead)(nil),      // 8: ctrlmsg.ResponseHead
	(*CtrlReqeust)(nil),       // 9: ctrlmsg.CtrlReqeust
	(*CtrlResponse)(nil),      // 10: ctrlmsg.CtrlResponse
}
var file_ctrlmsg_proto_depIdxs = []int32{
	5, // 0: ctrlmsg.PeerInfoResponse.infos:type_name -> ctrlmsg.PeerInfo
	7, // 1: ctrlmsg.CtrlReqeust.head:type_name -> ctrlmsg.ReqeustHead
	0, // 2: ctrlmsg.CtrlReqeust.register:type_name -> ctrlmsg.RegisterRequest
	2, // 3: ctrlmsg.CtrlReqeust.heartbeat:type_name -> ctrlmsg.HeartbeatRequest
	4, // 4: ctrlmsg.CtrlReqeust.peer_info:type_name -> ctrlmsg.PeerInfoRequest
	8, // 5: ctrlmsg.CtrlResponse.head:type_name -> ctrlmsg.ResponseHead
	1, // 6: ctrlmsg.CtrlResponse.register:type_name -> ctrlmsg.RegisterResponse
	3, // 7: ctrlmsg.CtrlResponse.heartbeat:type_name -> ctrlmsg.HeartbeatResponse
	6, // 8: ctrlmsg.CtrlResponse.peer_info:type_name -> ctrlmsg.PeerInfoResponse
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_ctrlmsg_proto_init() }
func file_ctrlmsg_proto_init() {
	if File_ctrlmsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ctrlmsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ctrlmsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ctrlmsg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ctrlmsg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ctrlmsg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeerInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ctrlmsg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ctrlmsg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeerInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ctrlmsg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqeustHead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ctrlmsg_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseHead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ctrlmsg_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CtrlReqeust); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ctrlmsg_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CtrlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_ctrlmsg_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*CtrlReqeust_Register)(nil),
		(*CtrlReqeust_Heartbeat)(nil),
		(*CtrlReqeust_PeerInfo)(nil),
	}
	file_ctrlmsg_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*CtrlResponse_Register)(nil),
		(*CtrlResponse_Heartbeat)(nil),
		(*CtrlResponse_PeerInfo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ctrlmsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ctrlmsg_proto_goTypes,
		DependencyIndexes: file_ctrlmsg_proto_depIdxs,
		MessageInfos:      file_ctrlmsg_proto_msgTypes,
	}.Build()
	File_ctrlmsg_proto = out.File
	file_ctrlmsg_proto_rawDesc = nil
	file_ctrlmsg_proto_goTypes = nil
	file_ctrlmsg_proto_depIdxs = nil
}
